### ISSUE TITLE
Highlighting text in Hugo Apero

### ISSUE THREAD

**Issue by JauntyJJS** [spcanelon/silvia#43]
Hi,

I was planning to write a Hugo Apero blog post on using the stringr package to clean up "untidy lipid column names" in the form "Lipid A (a/b/c)" to just "Lipid A".
Unfortunately, I realise that the regular expression to do this is not so simple and I need to highlight some text in my post.

I saw in this [webpage](https://silvia.rbind.io/blog/hello-hugo-apero/) that some of the text can be highlighted in green

![image](https://user-images.githubusercontent.com/9066508/132951891-f9456e4a-09b5-4346-a7fe-851b185c27cb.png)

As someone who is new in trying out Hugo Apero, is it possible to share how this is achieved in the rmarkdown file or is there some modification required in the Hugo Apero theme ?

May I ask if you have tried using Hugo Apero with the [flair](https://r-for-educators.github.io/flair/articles/how_to_flair.html) R package before ? 

I also tried to highlight the R code in Hugo Apero but was unsuccessful as the [white background in the code chunk got removed](https://github.com/hugo-apero/hugo-apero/issues/51)...

Thank you for your guidiance.

**Comment by spcanelon** [comment]
Hi @JauntyJJS,

What you were seeing highlighted in green was inline code, i.e. text surrounded by backticks ` `` `.
On my site, this styling is controlled by custom CSS code that styles all inline code that same way. Specifically this part of my custom sheet styles inline code (recently modified in commit https://github.com/spcanelon/silvia/commit/68bd737d8c28ca1a60b5ec9794885e32fd4ec5d0):

https://github.com/spcanelon/silvia/blob/68bd737d8c28ca1a60b5ec9794885e32fd4ec5d0/assets/custom.scss#L192-L215

If you are not familiar with CSS styling I can recommend [CSS first steps - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps) for well-organized learning resources. You could also copy the code above into your own `assets/custom.scss` file and learn by plarying around with the properties.

For more site color customization I recommend the [Style your site colors | Hugo Apéro](https://hugo-apero-docs.netlify.app/learn/color-themes/) post in the Hugo Apéro docs.

I haven't used `flair` so unfortunately I don't have any ideas on how to troubleshoot the issue you are having! The only thing I can think for you to try is to knit your post 🤷🏽‍♀️
